FROM golang:1.25

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/analyze ./cmd/analyze
COPY internals/domain/detection ./internals/domain/detection
COPY data ./data

RUN CGO_ENABLED=0 GOOS=linux go build -o analyze ./cmd/analyze

EXPOSE 9464

CMD ["./analyze", "--input-dir", "/app/data", "--listen", ":9464"]